### ISSUE TITLE
Question: Templated Set Request for CLI origin

### ISSUE THREAD

**Issue by bpchoi** [openconfig/gnmic#101]
Hi,
I've been trying to find a way to use request-file for CLI origin for Juniper device and 'gnmic' encloses payload with double quote.
This ascii_val seems not accepted as valid by the device.
Is there any way that work around this 'double quote' of ascii_val?

```
>gnmic -a bpchoi-vptx0-vmm:50051 -u xxxx -p xxxx--insecure --timeout 120s --log set --request-file intf_1_native_cli_request.yaml
2023/04/14 12:12:19.670919 [gnmic] version=0.29.0, commit=08d41dd, date=2023-02-21T09:10:29Z, gitURL=https://github.com/openconfig/gnmic, docs=https://gnmic.openconfig.net/
2023/04/14 12:12:19.670943 [gnmic] using config file ""
2023/04/14 12:12:19.671292 [gnmic] adding target {"name":"bpchoi-vptx0-vmm:50051","address":"bpchoi-vptx0-vmm:50051","username":"xxxx","password":"****","timeout":120000000000,"insecure":true,"skip-verify":false,"buffer-size":100,"retry-timer":10000000000,"log-tls-secret":false,"gzip":false,"token":""}
2023/04/14 12:12:19.671665 [config] trying to find variable file "/home/jnpr/intf_1_native_cli_request_vars.yaml"
2023/04/14 12:12:19.672782 [gnmic] sending gNMI SetRequest: prefix='', delete='[]', replace='[]', update='[path:{origin:"cli"} val:{ascii_val:""interfaces { et-0/0/1 { disable; speed 100g; } }""}]', extension='[]' to bpchoi-vptx0-vmm:50051
2023/04/14 12:12:19.672807 [gnmic] creating gRPC client for target "bpchoi-vptx0-vmm:50051"
2023/04/14 12:12:21.462737 [gnmic] target "bpchoi-vptx0-vmm:50051" set request failed: target "bpchoi-vptx0-vmm:50051" SetRequest failed: rpc error: code = InvalidArgument desc = syntax error;
target "bpchoi-vptx0-vmm:50051" set request failed: target "bpchoi-vptx0-vmm:50051" SetRequest failed: rpc error: code = InvalidArgument desc = syntax error;
Error: one or more requests failed
```
Thank you in advance,
Phil

**Comment by hellt** [comment]
Hi
can you post the contents of your `intf_1_native_cli_request.yaml`?

**Comment by bpchoi** [comment]
It's very simple example like below.
updates:
  - path: "cli:"
    value: interfaces { et-0/0/1 { disable; speed 100g;  }  }
    encoding: ascii
   
I tried several different ways and different values, but all same result, for your info.
Thanks for taking a look at this.

**Comment by karimra** [comment]
This is not supported yet, the request file is meant to be used with values type JSON or JSON_IETF.
I will add support for other encodings (and origin CLI) in next few days.

**Comment by bpchoi** [comment]
Thank you for working on it.
I wonder if file_name can be supported instead of 'value' for efficiency.
And CLI origin can be supported for 'delete' operation in template if it is not too much ask.
All these supported is to achieve mixed origin operations together ultimately.

**Comment by karimra** [comment]
@bpchoi can you give v0.30.0 a try? it should allow `replace` and `update` with cli origin.
The path should be `path: cli:/` (note the `/` at the end).
For delete, let's continue the conversation in #102

**Comment by bpchoi** [comment]
Yes, replace/update with cli origin works on v0.30.0.
Thanks much.
Could you help https://github.com/openconfig/gnmic/issues/102 about 'delete' for cli origin, too?
