### ISSUE TITLE
mTLS not working(certificate signed by unknown authority error)

### ISSUE THREAD

**Issue by Shikha-Chowdhary** [openconfig/gnmic#113]
Hello, 

I created a new CA cert, which then was used for signing a user cert-key pair using the XCA tool.
- The gnmic tunnel server always fails with "invalid CA authority error". 
- gNMIC version : 0.30.0
- Same certs are working fine with another TLS client-server with mTLS. 
- Sharing wireshark output, config file & client error.
_Is this a known issue , or am I not using the config options correctly?_

**1. Config file**
```yaml
insecure: true
username: ADMIN
password: ADMIN
log: true

tunnel-server:
  address: ":50051"
  tls:
    ca-file: /home/shikha/Client/rootca_2K.crt
    cert-file: /home/shikha/secure-tunnel/gnmi/cmd/gnmi_collector/certs1/cert.pem
    key-file: /home/shikha/secure-tunnel/gnmi/cmd/gnmi_collector/certs1/key.pem
    client-auth: "require-verify"
  target-wait-time: 20s
  enable-metrics: false
  debug: false
 ```
 
 **2. Client output**
 ```shell
2023/04/25 14:23:24.899447 /home/runner/work/gnmic/gnmic/app/outputs.go:27: [gnmic] starting output type file
2023/04/25 14:23:24.900211 /home/runner/work/gnmic/gnmic/outputs/file/file_output.go:204: [file_output:default-stdout] initialized file output: {"Cfg":{"FileName":"","FileType":"stdout","Format":"json","Multiline":true,"Indent":"  ","Separator":"\n","SplitEvents":false,"OverrideTimestamps":false,"AddTarget":"","TargetTemplate":"","EventProcessors":null,"MsgTemplate":"","ConcurrencyLimit":1000,"EnableMetrics":false,"Debug":false}}
2023/04/25 14:23:24.912009 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/grpclog/logger.go:53: [gnmic] [core] [Server #1] Server created
2023/04/25 14:23:24.919712 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/grpclog/logger.go:53: [gnmic] [core] [Server #1 ListenSocket #2] ListenSocket created
2023/04/25 14:23:52.364434 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/grpclog/logger.go:53: [gnmic] [core] [Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "ServerHandshake(\"192.168.0.15:62423\") **failed: tls: failed to verify client certificate: x509: certificate signed by unknown authority"**
```
**3. Wireshark snapshot**
- Always failing with bad cert error due to invalid CA authority.
![mTLS_fail](https://user-images.githubusercontent.com/37649729/234370668-cfe2dddf-71c3-4b48-a6ce-3bbc3de30eec.png)

**Comment by karimra** [comment]
Hi,

Either the client (router) certificate was not signed using this ca file `/home/shikha/Client/rootca_2K.crt` (can be verified using the `openssl verify` cmd).

Or gNMIc didn't read the `ca-file` attribute because of a malformed config file. 
Run the same `gnmic` command with `--debug`, it should dump the read configuration attribute to stderr.

**Comment by Shikha-Chowdhary** [comment]
_Thanks_

1.**openssl verify** is all good.
- openssl verify -verbose -CAfile rootca_2K.crt  client2.crt 
client2.crt: OK
bash-4.2$ 

**2. The gNMIC is also reading the "ca-file" correctly** 
2023/04/26 04:03:43.986735 /home/runner/work/gnmic/gnmic/app/app.go:269: [gnmic] tunnel-server/tls/ca-file='/home/shikha/Client/rootca_2K.crt'(string)
2023/04/26 04:03:43.987677 /home/runner/work/gnmic/gnmic/app/app.go:269: [gnmic] tunnel-server/tls/cert-file='/home/shikha/secure-tunnel/gnmi/cmd/gnmi_collector/certs1/cert.pem'(string)
2023/04/26 04:03:43.988611 /home/runner/work/gnmic/gnmic/app/app.go:269: [gnmic] tunnel-server/tls/client-auth='require-verify'(string)
...

3. Also, it's failing with "unknown authority" error with self signed certs as well. What should be value of **"ca-file"** in case of self signed? 

_Debugging further at server's end, if it's sending the certificate correctly._

**Comment by karimra** [comment]
Can you run this command to check which issuer the tunnel server expects:
`openssl s_client -connect <gnmic-IP>:50051 | openssl x509 -noout -issuer`

**Comment by Shikha-Chowdhary** [comment]
Using the same CA certificate for signing server and client certs. The client validates the server certs, but the tunnel sever fails with "**unknown authority**" error.
- Sharing the certs too 
[client3.zip](https://github.com/openconfig/gnmic/files/11352879/client3.zip)
bash-4.2$2 openssl s_client -connect 10.179.193.207:50051 -cert client3.crt -key client3.pem -state -quiet| openssl x509 -noout -issuer
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
SSL_connect:SSLv3 read server hello A
depth=0 C = IN, ST = UP, L = abc, O = abc3, CN = servershikha
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = IN, ST = UP, L = abc, O = abc3, CN = servershikha
verify error:num=21:unable to verify the first certificate
verify return:1
SSL_connect:SSLv3 read server certificate A
SSL_connect:SSLv3 read server key exchange A
SSL_connect:SSLv3 read server certificate request A
SSL_connect:SSLv3 read server done A
SSL_connect:SSLv3 write client certificate A
SSL_connect:SSLv3 write client key exchange A
SSL_connect:SSLv3 write certificate verify A
SSL_connect:SSLv3 write change cipher spec A
SSL_connect:SSLv3 write finished A
SSL_connect:SSLv3 flush data
SSL3 alert read:fatal:bad certificate
SSL_connect:failed in error
140319461410704:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:s3_pkt.c:1493:SSL alert number 42
140319461410704:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
unable to load certificate
139748125353872:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE
bash-4.2$

- Tunnel server error 
...
2023/04/28 07:06:46.573406 /home/runner/work/gnmic/gnmic/app/app.go:269: [gnmic] tunnel-server/tls/ca-file='/home/shikha/Client/client3/rootca3.crt'(string)
2023/04/28 07:06:46.574060 /home/runner/work/gnmic/gnmic/app/app.go:269: [gnmic] tunnel-server/tls/cert-file='/home/shikha/Client/client3/server3.crt'(string)
2023/04/28 07:06:46.574751 /home/runner/work/gnmic/gnmic/app/app.go:269: [gnmic] tunnel-server/tls/client-auth='require-verify'(string)
2023/04/28 07:06:46.575333 /home/runner/work/gnmic/gnmic/app/app.go:269: [gnmic] tunnel-server/tls/key-file='/home/shikha/Client/client3/server3.pem'(string)
2023/04/28 07:06:46.575349 /home/runner/work/gnmic/gnmic/app/app.go:269: [gnmic] use-tunnel-server='true'(bool)
...
...
2023/04/28 07:06:46.582010 /home/runner/work/gnmic/gnmic/outputs/file/file_output.go:204: [file_output:default-stdout] initialized file output: {"Cfg":{"FileName":"","FileType":"stdout","Format":"json","Multiline":true,"Indent":"  ","Separator":"\n","SplitEvents":false,"OverrideTimestamps":false,"AddTarget":"","TargetTemplate":"","EventProcessors":null,"MsgTemplate":"","ConcurrencyLimit":1000,"EnableMetrics":false,"Debug":false}}
2023/04/28 07:06:46.584201 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/grpclog/logger.go:53: [gnmic] [core] [Server #1] Server created
2023/04/28 07:06:46.584791 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/grpclog/logger.go:53: [gnmic] [core] [Server #1 ListenSocket #2] ListenSocket created
2023/04/28 07:06:51.895892 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/grpclog/logger.go:53: [gnmic] [core] [Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "ServerHandshake(\"10.179.193.207:41558\") failed: tls: failed to verify client certificate: x509: certificate signed by unknown authority"

**Comment by Shikha-Chowdhary** [comment]
Hey, 

Is there any update on this issue? The same set of certs are working with **openssl s_client and s_server** utility, but failing with tunnel server.

**1. s_client and s_server**
bash-4.2$ openssl s_client -connect 10.179.193.207:50051 -cert /home/shikha/certificates/certs/client/client.crt -key /home/shikha/certificates/certs/client/client.key -state -quiet -CAfile ~/cert.pem  
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
SSL_connect:SSLv3 read server hello A
SSL_connect:SSLv3 read server certificate A
SSL_connect:SSLv3 read server key exchange A
SSL_connect:SSLv3 read server certificate request A
SSL_connect:SSLv3 read server done A
SSL_connect:SSLv3 write client certificate A
SSL_connect:SSLv3 write client key exchange A
SSL_connect:SSLv3 write certificate verify A
SSL_connect:SSLv3 write change cipher spec A
SSL_connect:SSLv3 write finished A
SSL_connect:SSLv3 flush data
SSL_connect:SSLv3 read server session ticket A
SSL_connect:SSLv3 read finished A

bash-4.2$ openssl s_server -accept 50051 -cert /home/shikha/secure-tunnel/gnmi/cmd/gnmi_collector/certs1/cert.pem -CAfile /home/shikha/certificates/certs/client/ClientCA.crt -key /home/shikha/secure-tunnel/gnmi/cmd/gnmi_collector/certs1/key.pem  -Verify 1 -state -quiet
verify depth is 1, must return a certificate
SSL_accept:before/accept initialization
SSL_accept:SSLv3 read client hello A
SSL_accept:SSLv3 write server hello A
SSL_accept:SSLv3 write certificate A
SSL_accept:SSLv3 write key exchange A
SSL_accept:SSLv3 write certificate request A
SSL_accept:SSLv3 flush data
SSL_accept:SSLv3 read client certificate A
SSL_accept:SSLv3 read client key exchange A
SSL_accept:SSLv3 read certificate verify A
SSL_accept:SSLv3 read finished A
SSL_accept:SSLv3 write session ticket A
SSL_accept:SSLv3 write change cipher spec A
SSL_accept:SSLv3 write finished A
SSL_accept:SSLv3 flush data 


**2. s_client and tunnel server** 
bash-4.2$ openssl s_client -connect 10.179.193.207:50051 -cert /home/shikha/certificates/certs/client/client.crt -key /home/shikha/certificates/certs/client/client.key -state -quiet -CAfile ~/cert.pem  
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
SSL_connect:SSLv3 read server hello A
SSL_connect:SSLv3 read server certificate A
SSL_connect:SSLv3 read server key exchange A
SSL_connect:SSLv3 read server certificate request A
SSL_connect:SSLv3 read server done A
SSL_connect:SSLv3 write client certificate A
SSL_connect:SSLv3 write client key exchange A
SSL_connect:SSLv3 write certificate verify A
SSL_connect:SSLv3 write change cipher spec A
SSL_connect:SSLv3 write finished A
SSL_connect:SSLv3 flush data
SSL3 alert read:fatal:bad certificate
SSL_connect:failed in error
139631540815760:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:s3_pkt.c:1493:SSL alert number 42
139631540815760:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
bash-4.2$ 

...nSocket created
2023/05/17 03:08:41.142065 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/grpclog/logger.go:53: [gnmic] [core] [Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "ServerHandshake(\"10.179.193.207:52524\") failed: tls: failed to verify client certificate: x509: certificate signed by unknown authority"

**Comment by karimra** [comment]
v0.31.0 is out it should have a fix for your issue.

**Comment by Shikha-Chowdhary** [comment]
> v0.31.0 is out it should have a fix for your issue.

The latest version of gNMIC resolves the above issue.
Thanks a lot
