### ISSUE TITLE
using target name with http target loader 

### ISSUE THREAD

**Issue by jrametta** [openconfig/gnmic#141]
Hi, I am using dynamic HTTP target loader and run into issue where gnmic continuously adds the same device.

For example, my http url can return this data to gnmic:

```
{
  "pan1:50051": {
    "name": "bob",
    "username": "admin",
    "password": "asdf",
    "subscriptions": [
      "pan-interface"
    ]
  }
}
```

in the gnmic logs, i continuously see this message every watch interval:

```
gnmic1        | 2023/06/03 03:23:00.146635 [gnmic] target "bob" deleted from config
gnmic1        | 2023/06/03 03:23:00.146779 [gnmic] target "bob": listener stopped
gnmic1        | 2023/06/03 03:23:00.146805 [gnmic] adding target {"name":"bob","address":"pan1:50051","username":"admin","password":"****","timeout":10000000000,"insecure":true,"skip-verify":false,"subscriptions":["pan-interface"],"buffer-size":100,"retry-timer":10000000000,"log-tls-secret":false,"gzip":false,"token":""}
gnmic1        | 2023/06/03 03:23:00.146851 [gnmic] queuing target "bob"
gnmic1        | 2023/06/03 03:23:00.146869 [gnmic] subscribing to target: "bob"

```

On the target device, I can see that the number of persistently established tcp connections from gnmic continuously increases.  If i remove the "name" key/value pair from the above json, then the problem goes away.

I can supply simple docker-compose to reproduce if needed.

loader config:
```
loader:
  type: http
  url: "http://10.196.21.67:9999/devices"
  interval: 30s
  start-delay: 0s
  enable-metrics: true
```

thank you for continuous development!

**Comment by karimra** [comment]
Good catch, I see where the issue is, I will try to fix it ASAP.
