### ISSUE TITLE
New docker container image with latest gnmic version

### ISSUE THREAD

**Issue by bpchoi** [openconfig/gnmic#145]
The latest gnmic container image  from Dockerhub or GitHub container registries have v0.26.0 which is about a year ago.
Could we get new latest gnmic container image?
Thank you.

**Comment by hellt** [comment]
Hi. 
Images are up to date https://github.com/openconfig/gnmic/pkgs/container/gnmic

**Comment by bpchoi** [comment]
I appreciate sharing this hidden gem here. 
Cheers.
