### ISSUE TITLE
FR: Support stdin as input file

### ISSUE THREAD

**Issue by jbemmel** [openconfig/gnmic#146]
For use in Unix pipelines:

```
<some command that generates YAML> | gnmic set --replace-path /configure/router[router-name=Base] --stdin yaml
```

We can discuss about the syntax; other tools use '-' as filename for stdin, the format could be auto-detected as well

**Comment by karimra** [comment]
The '-' syntax should be supported now. Did it fail for you?

**Comment by jbemmel** [comment]
I could not find it in the documentation, I did not try

**Comment by karimra** [comment]
We had this same conversation a couple of years ago: https://github.com/karimra/gnmic/issues/369
