### ISSUE TITLE
event-date-string: Can't format base path timestamp

### ISSUE THREAD

**Issue by smalenfant** [openconfig/gnmic#148]
I would like to be able to format the root "timestamp" so I can debug messages on the screen. It seems like we can only use it with value-names or tag-names.

There is no documentation for this processor but only 1 example, although one can figure it out that `tag-names` or `value-names` need to be used.

The primary goal here was to reduce precision (from ns to s/ms) to allow the merge processors to allow multiple document to be merged together. Although this might not work when they are not part of the same notification response.

The second goal was to reduce precision since Elasticsearch can't format a nanosecond epoch using their internal templates. I believe Telegraf reduce the timestamp to seconds when using JSON output.

**Comment by smalenfant** [comment]
What would be the format specified to output Unix or UnixMilli?

**Comment by karimra** [comment]
That processor does not operate on the event timestamp, only on timestamps present as tags or values as you already figured out.

To reduce the timestamp precision your only option is to use the starlak processor and import the time module. It's fairly easy to write a short script that changes the timestamp precision. But I do understand that it should be easier than that, I will look into adding that to the processor.

Merging messages can also be done using starlark, example [here](https://gnmic.openconfig.net/user_guide/event_processors/event_starlark/#set-an-interface-description-as-a-tag)

**Comment by smalenfant** [comment]
Thanks for pointing out the description example for Starlark. This is actually really helpful, seems like whoever is working on gnmic are coming across similar challenges.

Is there a place to discuss about this project or get help? Slack or others?

**Comment by karimra** [comment]
You can get help here with issues. 
There is a discord channel for gnmic under the containerlab server as well.
