### ISSUE TITLE
Feature Request: make InfluxDB health check optional

### ISSUE THREAD

**Issue by dpajin** [openconfig/gnmic#15]
Would it be possible to make InfluxDB health check optional?
The use case for this is writing to InfluxDB or other places over Telegraf instance. Telegraf's input plugins like influxdb_listener or  influxdb_v2_listener or http_v2_listener do not support "/health" endpoint for this purpose.
The use case for using Telegraf is post processing of the submitted measurements or writing to multiple outputs

**Comment by karimra** [comment]
Yes this is possible, will look into it.

**Comment by hellt** [comment]
@dpajin i am curious which outputs you use with telegraf which gnmic doesn't have?

**Comment by dpajin** [comment]
@hellt I don't have any specific output in mind, I mentioned it in the context of writing to multiple instances of InfluxDB, but after second though I guess that can be achieved with gnmic. 
My interest also is post processing. It is really nice that gnmic has a rich set of processors which can do a lot of manipulations of the metrics. However, there can always be some use cases which cannot be addressed. Telegraf has "starlark" processor, which gives some more flexibility in this context.
One use case that I was thinking about was for example "oper-status" interface state, which is with gNMI/OpenConfig already  returned as a string (UP/DOWN). On the other side, usually this is treated as a metric which has to be numerical, if you want to graph it over time or alert, etc... so there is a need to convert those enum values into int values. However, I figured out how to do it with gnmic.
Another use case is performing some math operations between multiple returned values.

**Comment by hellt** [comment]
@dpajin yes, it looks like this is all possible with gnmic. 

Multiple output instances are supported by defining several outputs.

Converting strings maps to chosen ints is typically done with https://gnmic.openconfig.net/user_guide/event_processors/event_strings/#replace where one string (e.g. "UP") is converted to another string (e.g. "1") and the output takes care of converging the string to int/float afterwards

```yaml
processors:
  # processor name
  up-down-map:
    # processor type
    event-strings:
      value-names:
        - /interface/oper-state
      transforms:
        # strings function name
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
```

For advanced transformations you can have a look at the JQ processor, that gives you quite some flexibility in what you wanna do with the ingested data https://gnmic.openconfig.net/user_guide/event_processors/event_jq/

**Comment by dpajin** [comment]
@hellt thanks for suggestions - that's exactly what I have done for enum mapping and I will take a look more into JQ processor.
