### ISSUE TITLE
Wrong path in config option

### ISSUE THREAD

**Issue by robindaumann** [openconfig/gnmic#161]
The usage output says `gnmic.yaml` instead of `.gnmic.yaml`.

```
--config string            config file (default is $HOME/gnmic.yaml)
```

Also the [documentation page](https://gnmic.openconfig.net/user_guide/configuration_file/) does not mention anything about the default configuration file name.

**Comment by karimra** [comment]
you are right, the usage output is outdated.
the documentation page that explains the config files name and location is [here](https://gnmic.openconfig.net/user_guide/configuration_intro/#file-configuration)

**Comment by robindaumann** [comment]
Thanks a lot for providing the correct documentation and fixing the usage text.
