### ISSUE TITLE
Starlark processor "local variable referenced before assignment"

### ISSUE THREAD

**Issue by netixx** [openconfig/gnmic#164]
Hello,

I wrote a small starlark processor to count the number of events with a given value I receive from the router (the router doesn't provide a count of the entries in the fib, so I opted to have a counter follow each time a prefix is inserted).

I am using this:
```
processors:
  update-count:
    event-starlark:
      debug: false
      source: |

        ev_count = 0

        def apply(*events):
          evs = []
          for e in events:
            if e.values.get('/state/router/route-fib/ipv4/route/last-updated', False):
              ev_count += 1
              new_ev = Event(e.name, e.timestamp, e.tags)
              new_ev.values["count"] = ev_count
              evs.append(new_ev)
          return evs
```

Following the [example](https://gnmic.openconfig.net/user_guide/event_processors/event_starlark/#set-an-interface-description-as-a-tags), I think it should work, however, it's throwing the following error while running:
```
2023/06/27 12:30:33.011395 /home/runner/work/gnmic/gnmic/formatters/event_starlark/event_starlark.go:152: [event-starlark] failed to run script: local variable ev_count referenced before assignment
```

I tried to change the type of ev_count to a dummy dict (`ev_count = {'x': 0}`), but then I got the following error:
```
2023/06/27 12:20:05.924913 /home/runner/work/gnmic/gnmic/formatters/event_starlark/event_starlark.go:152: [event-starlark] failed to run script: cannot insert into frozen hash table
```

I don't know what the issue could be at this point... Is there something wrong with my code, or is it a limitation of the starlark engine ? I am running v0.31.1 by the way.

Thank you.

**Comment by karimra** [comment]
Hi, 

You can use the `cache` dict, just like the example.
The `cache` dict is a predeclared global dict that can be used for user-defined mutable global variables.

**Comment by netixx** [comment]
ah thanks, I thought "cache" was just an example variable name!
