### ISSUE TITLE
Feature request: Make username,password optional parameter

### ISSUE THREAD

**Issue by mukuntharajaa** [openconfig/gnmic#18]
If some software follows gNMI/gNOI spec to implement certain services ( eg: certificate management ), it would not be needed to add username based authentication to this service as authentication would be ensured in various other methods.

In such case, it becomes cumbersome to use "gnmic" as it always prompts for username and password. 

It would be nicer to make username/password prompt as optional or introduce a flag with which there should not be any need to username and password.

**Comment by karimra** [comment]
Agree, this has been asked multiple times, I just never got to it.
