### ISSUE TITLE
Unable to install the latest version on a Mac M1 laptop

### ISSUE THREAD

**Issue by dnikoliouk-dn** [openconfig/gnmic#184]
` % bash -c "$(curl -sL https://get-gnmic.openconfig.net)"
bash: line 134: /usr/local/bin/gnmic: cannot execute binary file
gnmic 0.31.4 is available. Changing from version .
Downloading https://github.com/openconfig/gnmic/releases/download/v0.31.4/gnmic_0.31.4_darwin_aarch64.tar.gz
tar: Error opening archive: Unrecognized archive format
Failed to install gnmic
        For support, go to https://github.com/openconfig/gnmic/issues`

gnmic_0.31.4_darwin_aarch64.tar.gz file does not exist.

**Comment by karimra** [comment]
Assuming this is solved, feel free to reopen if not.
