### ISSUE TITLE
Validate mode, stream mode and encoding

### ISSUE THREAD

**Issue by vincentbernat** [openconfig/gnmic#187]
Hey!

`--mode`, `--stream-mode` and `--encoding` are not validated at all. It's easy to use for example `--stream-mode onchange` and to not get a single error. For `--stream-mode`, there is no validation in `CreateSubscribeRequest()`: `gnmi.SubscriptionMode_value[strings.Replace(strings.ToUpper(sc.StreamMode), "-", "_", -1)]` will return `gnmi.SubscriptionMode_SAMPLE` when using non-existent values. For everything else, the subscription happens inside a go routine displaying the error to an (unconfigured) logger and not aborting on error.

I think the right fix would be for `SubscriptionConfig` to have some kind of validation (and ideally to directly use the right types instead of string). However, as this would change the public API, this may not be possible.

**Comment by karimra** [comment]
Yes, gNMIc is also used to validate gNMI servers behavior, so there is a use in sending erroneous values or invalid combinations.
Some devices use encodings that are not defined by the gNMI spec.

**Comment by vincentbernat** [comment]
I don't understand. Currently, the wrong encoding or subscription mode leads to an error that is not displayed and ignored (in stream mode). The wrong stream mode is silently corrected to "sample".

```
 02:06 ❱ gnmic --insecure  -a 127.0.0.1:57400 --username admin --password admin --encoding json_ietfff sub --mode once --path /configure/system/name --path /configure/port/description --path /configure/router/interface/description --path /state/router/interface/if-index --path /state/port/ethernet/oper-speed
option Encoding: invalid value: json_ietfff
Error: one or more requests failed
 02:06 ❱ gnmic --insecure  -a 127.0.0.1:57400 --username admin --password admin --encoding json_ietf sub --mode oncef --path /configure/system/name --path /configure/port/description --path /configure/router/interface/description --path /state/router/interface/if-index --path /state/port/ethernet/oper-speed
^C
received signal 'interrupt'. terminating...
```

**Comment by karimra** [comment]
My bad, I assumed you were using the API for akvorado.

When using the cli, not all values are accepted. The errors are logged in the case of a subscribe RPC and do not lead to the whole command failing because there might be other subscriptions running fine.
You can add the flag --log or --debug to initialize the logger.

Can you show an example of a wrong stream mode being corrected to "sample" by gNMIc cli ?

**Comment by vincentbernat** [comment]
You are right, I get an error when enabling the logger. I was assuming this was silently converted to sample because I missed the call to `api.SubscriptionMode()` in `CreateSubscribeRequest()`.

It is still confusing that typing `onchange` is not providing any error. I spend some time thinking that the problem was on the remote device.

**Comment by karimra** [comment]
With the latest version (v0.31.7) you should get a config error when you specify an unknown mode, stream-mode or encoding.
`config error: subscription default-1691123702: unknown stream-mode type "onchange"`
