### ISSUE TITLE
Password with $ failing

### ISSUE THREAD

**Issue by ianbarrere** [openconfig/gnmic#230]
I noticed that when using a password with a $ in it I would not be able to authenticate to the endpoint. It would return this error after some seconds:

`target "10.211.15.115:50051" get request failed: "10.211.15.115:50051" GetRequest failed: rpc error: code = Unauthenticated desc = Authentication failed
target "10.211.15.115:50051" get request failed: "10.211.15.115:50051" GetRequest failed: rpc error: code = Unauthenticated desc = Authentication failed`

When I changed the password to something simpler it started working. Not a huge issue, but something to be aware of. Endpoint was Cisco Nexus fwiw.

**Comment by karimra** [comment]
How was the password set? In the cli with `-p` or in the config file ?

**Comment by ianbarrere** [comment]
I was passing it in on the CLI with -p. Hadn't tried the config file approach.

**Comment by hellt** [comment]
worth trying to wrap password in single quotes like 
```
-p 'my$pwd'
```

**Comment by ianbarrere** [comment]
> worth trying to wrap password in single quotes like
> 
> ```
> -p 'my$pwd'
> ```

🤦‍♂️ single quotes works. I tried with double quotes to no avail before opening the issue.
