### ISSUE TITLE
gnmic skip-verify mode does not work with SRL anymore

### ISSUE THREAD

**Issue by jk2lx** [openconfig/gnmic#231]
Previously it was possible to get gnmi metrics with the following gnmic command from an SRL device, but for whatever reason this now doesn't work anymore and instead SRL is logging "wrong version number".

gnmic --skip-verify -a edge2 -u *** -p *** -e ascii get --path /interface/transceiver

SRL config (gnmi and TLS parts only):
set / system gnmi-server admin-state enable
set / system gnmi-server commit-save true
set / system gnmi-server network-instance mgmt admin-state enable
set / system gnmi-server network-instance mgmt tls-profile tls-profile
set / system tls server-profile tls-profile key ***
set / system tls server-profile tls-profile certificate ***
set / system tls server-profile tls-profile authenticate-client false
set / system tls server-profile tls-profile trust-anchor  ***

SRL Logs:
2023-09-25T10:06:11.400262+00:00 edge2 sr_gnmi_server: debug|3773|2723733|00568|W: gnmi_grpc ssl_transport_security.cc:1233     SrlGrpcLog  Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number.

**Comment by hellt** [comment]
Hi @jk2lx 
what srlinux version (`show version`) and gnmic version are you running?

**Comment by jk2lx** [comment]
SR Linux v22.6.4 and gnmic 0.32.0

**Comment by jk2lx** [comment]
I have seen "wrong version number" with other devices where openssl could not validate the device's certs.

In this case though gnmic runs with skip-verify and the SRL device is configured with "authenticate-client false" so neither side should validate the other side's cert. Has the skip-verify behaviour changed?

**Comment by karimra** [comment]
No change in the skip-verify behavior, the client does not verify the server's certificate chain and hostname. 
But the TLS handshake and version negotiation still needs to be successful.
When you say it previously worked, did it work with a different version of SRL/gnmic ? Same or different setup ?

**Comment by jk2lx** [comment]
There were no changes with gnmic/SRL, it turned out that the firewall only passed grpc and not ssl on port 57400...
Thanks anyway, helped me narrowing down the culprit.
