### ISSUE TITLE
Kafka output split-events causing marshal errors for kafka input

### ISSUE THREAD

**Issue by Sparc0** [openconfig/gnmic#253]
Kafka output has a parameter split-events. 
Having it on true will cause marshal errors on kafka input.

A split-events: boolean for the kafka input also.

**Comment by karimra** [comment]
If the event messages are going to be read by the Kafka gNMIc input why split them? 
The split events on the Kafka output was added to allow apache druid to ingest event messages from Kafka.

**Comment by Sparc0** [comment]
Basically the same idea, that i want to reuse the same topic in Kafka with gnmic and other platforms that gnmic dont support.

I can solve it by having 2 outputs in gnmic or another instance of gnmic that only split the events but it will require more storage in kafka and more compute to parse the metrics twice.

**Comment by karimra** [comment]
Added in #255
