### ISSUE TITLE
Help with event-processor : event-strings

### ISSUE THREAD

**Issue by baijuw** [openconfig/gnmic#297]
I am trying to write a processor to convert basic "up" and "down" strings to integers before passing it on to Prometheus. The value I am after is oper-state from SR Linux nodes. When I subscribe on CLI I can see the output. However after applying event-processor, I am missing this bit of data. The rest of the paths that I am subscribing do show up in Prometheus. 

```

{
  "source": "x.x.x.x",
  "subscription-name": "srl_leaf_uplink_stats",
  "timestamp": 1700064815400100393,
  "time": "2023-11-15T16:13:35.400100393Z",
  "updates": [
    {
      "Path": "interface[name=ethernet-1/4]/oper-state",
      "values": {
        "interface/oper-state": "up"
      }
    }
  ]
}
```

The processor I am using is as follows:-
```
outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - string-to-int

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"

  string-to-int:
    event-strings:
      values:
        - "up"
        - "down"
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: 1
        - replace:
            apply-on: "value"
            old: "down"
            new: 0

```

Am I missing something here? I have tried options like "interface/oper-state", ".*oper-state" etc for  value-names: thinking it is an issue with matching. It still does not seem to work. Hopefully I am using the right syntax here.

**Comment by karimra** [comment]
Try by adding double quotes around the `0` and `1. `new: "0"` and `new: "1"`.
Check gNMIc logs, there should be a complaint about the processor not being properly initialized.

**Comment by flyboyjon** [comment]
Here is the working processor I'm using :

  # Convert Status string values to numerical representations
  interface-status-convert:
    event-strings:
      value-names:
        - "/interfaces/interface/state/oper-status"
        - "/interfaces/interface/state/admin-status"
        - "/interfaces/interface/subinterfaces/subinterface/state/oper-status"
        - "/interfaces/interface/subinterfaces/subinterface/state/admin-status"
      transforms:
        - replace:
            apply-on: "value"
            old: "^UP$"
            new: "1"
        - replace:
            apply-on: "value"
            old: "^DOWN$"
            new: "2"
        - replace:
            apply-on: "value"
            old: "^TESTING$"
            new: "3"
        - replace:
            apply-on: "value"
            old: "^UNKNOWN$"
            new: "4"
        - replace:
            apply-on: "value"
            old: "^DORMANT$"
            new: "5"
        - replace:
            apply-on: "value"
            old: "^NOT_PRESENT$"
            new: "6"
        - replace:
            apply-on: "value"
            old: "^LOWER_LAYER_DOWN$"
            new: "7"

**Comment by baijuw** [comment]
Hi I got it working with the following. So quote are mandatory even for INT and Float. This is the one that tripped me .

```
  string-to-int:
    event-strings:
      value-names:
        - "oper-state"
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
```

However there somethings I learnt. 
1. We know that the **value-names:** has to match what is provided. This was one is tricky. As you note the subscription response output you get from gnmic cli put this as (Sample output in the original post)
```
values": {
        "interface/oper-state": "up"
      }
 ```

So from this output the field value-names:  has to be "interface/oper-state". This however does not work. 
 
 2. To get the real value to use for the field  value-names: I had to run a debug on prom output and watch what it is sending. There I saw the field received is different 
  
 ```
 02.167039 [prometheus_output:prom] got event to store: {"name":"srl_spine_uplink_oper","timestamp":1700116316366013440,"tags":{"interface_name":"ethernet-1/3","source":"x.x.x.x","subscription-name":"srl_spine_uplink_oper"},"values":{"oper-state":"up"}}
```
As you see, here the value-name is just "oper-state" vs "interface/oper-state"
 
 @flyboyjon : I tried the value-names you provided. But they dont seem to work:-
 ```
 **not working**
 value-names:
- "/interfaces/interface/state/oper-status"
```
 Thanks for the help though.

**Comment by karimra** [comment]
@baijuw The value name is `oper-state` and not `interface/oper-state` because you changed it with the `trim-prefixes` processor.

**Comment by baijuw** [comment]
Ok to close this. Got all the help I need.
