### ISSUE TITLE
gnmic install script result in binary missing read permission

### ISSUE THREAD

**Issue by shichuzhu** [openconfig/gnmic#309]
https://github.com/openconfig/gnmic/blob/d461fa9193271d3b01d38766a7680c63a6e735f5/install.sh#L196

```
$ ls -al /usr/local/bin/
-rwxr-xr-x 1 root root 105652224 Dec  5 19:47 gnmic
```

This result in gnmic giving 'Permission denied' error.

Suggesting `chmod 755 /usr/local/bin/gnmic`

**Comment by bstoll** [comment]
I think your `ls` output was wrong:

```
$ ls -la /usr/local/bin/gnmic
-rwxr-x--- 1 root root 105652224 Dec  5 23:00 /usr/local/bin/gnmic
```

The umask is 0027 in this environment so that's why the permissions got lost.  Most distros use 0022 I think so this may not be a common problem.  I think the "fix" is the same either way though.

**Comment by shichuzhu** [comment]
Thanks @bstoll for correcting it. Yes, my environment happens to have umask 027.
