### ISSUE TITLE
unclear usage of proto encoding

### ISSUE THREAD

**Issue by daldoyle** [openconfig/gnmic#31]
Hi there,

This may be more of a documentation / noob question than anything else. I have a Nokia running the following, as described by the capabilities request

```
gNMI version: 0.7.0
supported models:
  - nokia-conf, Nokia, 20.10.R8
  - nokia-state, Nokia, 20.10.R8
  - nokia-li-state, Nokia, 20.10.R8
  - nokia-li-conf, Nokia, 20.10.R8
supported encodings:
  - JSON
  - BYTES
  - PROTO
```

The tool has worked great with --encoding json or --encoding bytes and I am able to do get all of what I need working just fine like that. I am now trying to test any efficiency / performance differences between that and the proto encoding and running into a wall.

After some reading up I went and grabbed the Nokia proto files from here https://github.com/nokia/protobufs. Looking at the contents of the file I can see '/state/system/cpu' inside of it. However, if I run a command like this...

`gnmic -d --proto-dir 7x50_protobufs/latest_sros_22.10 --proto-file nokia-sros-combined-model.proto -a $host:$port -u $user -p $password --path '/state/system/cpu[sample-period=1]/summary' --mode once --encoding proto`

It shows that it's loading up the proto files, however I end up with output like this:
```
{
  "source": "$host:$ip",
  "subscription-name": "default-1671720379",
  "timestamp": 1671720414861904391,
  "time": "2022-12-22T06:46:54.861904391-08:00",
  "updates": [
    {
      "Path": "",
      "values": {
        "": "Qh2iAhryARcKAggBkgMQCg4KBQipkM4HEgUIkE4QAg=="
      }
    }
  ]
}
```

I'm not really sure how to go about troubleshooting this. If I try other proto files in that github repo (or don't specify it at all) I get similar results, so maybe that means that the proto files are not correct? Maybe my usage is incorrect? There isn't specifically a "22.10.r8" tag in that repo, only a ".r1" but it isn't clear to me if that matters or not. If it is an invalid file, maybe some sort of warning about being unable to decode would be helpful as an indicator that something is up?

Apologies if this is a completely newbie question or I'm off entirely in the wrong direction. I haven't been able to find much in the way of examples of people using protobufs successfully so I thought I would try here.

Thanks.

**Comment by daldoyle** [comment]
Any thoughts on what might be going on here? I've tried a few other odds and ends but still don't seem to be able to get it going successfully.

**Comment by karimra** [comment]
I'm not sure if you need a different set of proto files for R8 vs R1, worth asking a nokia representative.

If gNMIc fails to decode a proto_bytes value when there was a set of proto files loaded you would see a log message like:
`target "TARGET_NAME": failed to decode proto bytes: ERROR`
