### ISSUE TITLE
gnmic dropping certain paths when using event/prometheous output that do show up in json formatted output

### ISSUE THREAD

**Issue by mdebord-dlr** [openconfig/gnmic#335]
I am having an issue with gnmic not presenting a value when using prometheus output. The data definitely exists in gnmi data when querying gnmi directly.

In order to debug, I changed the **output** to `file`, using `event` format. The data does not exist in my event formatted debug output. 

So I then changed to `json` format, and the desired metric shows up:

```
      {
        "Path": "defaultStats/latency",
        "values": {
          "defaultStats/latency": 0.2329999953508377
        }
      },
```

From what I can tell, 0.2329999953508377 looks like it would be a valid value. I've tried various versions of gnmic, including the latest 0.34.3

I am using json/event solely for debugging. My end goal is to use a **subscribe** and processors to get **prometheus** output.

**Comment by karimra** [comment]
Can you share the output with format `prototext`?

**Comment by mdebord-dlr** [comment]
HI @karimra , thanks, here is a snip using prototext: 

```
  update:  {
    path:  {
      elem:  {
        name:  "defaultStats"
      }
      elem:  {
        name:  "latency"
      }
    }
    val:  {
      double_val:  0.05999999865889549
    }
  }
  ```

**Comment by karimra** [comment]
Thanks, double values are not handled when using the event format, will fix that shortly.

**Comment by mdebord-dlr** [comment]
>will fix that shortly.

You are amazing!!! Life saver.

**Comment by karimra** [comment]
@mdebord-dlr can you give v0.35.0 a try ? Thanks

**Comment by mdebord-dlr** [comment]
> @mdebord-dlr can you give v0.35.0 a try ? Thanks

I'm seeing results now @karimra thanks. Looking good. FYI this was on Arista EOS 4.3x platform if you were wondering.
