### ISSUE TITLE
The sarama kafka library has changed ownership and is no longer receiving updates

### ISSUE THREAD

**Issue by alibresco** [openconfig/gnmic#347]
Earlier this year, the sarama kafka library changed ownership from `Shopify/sarama` to `IBM/sarama`: https://github.com/IBM/sarama/issues/2461

As a result, the library is no longer receiving dependabot upgrades and will need to be manually upgraded once.

A wrinkle here is that gnmic depends on https://github.com/damiannolan/sasl which also depends on `Shopify/sarama`. Paths forward seem to be getting that library moved to `IBM/sarama` or just ripping out that library (it's not much code at all).

**Comment by karimra** [comment]
Yes. I was waiting for an alternative to https://github.com/damiannolan/sasl to pop up for the IBM one.

**Comment by alibresco** [comment]
Cool, I made an issue over there: https://github.com/damiannolan/sasl/issues/3

**Comment by karimra** [comment]
last version uses IBM/sarama, thanks for reporting
