### ISSUE TITLE
Race condition to use tg.SubscribePoll

### ISSUE THREAD

**Issue by vincentbernat** [openconfig/gnmic#353]
Hey!

This is difficult to use `tg.SubscribePoll()` safely as we need to subscribe inside a go routine, then poll only when the goroutine has sufficiently moved forward to register the new subscription.

**Comment by vincentbernat** [comment]
Also, I am unable to make it work at all:
- only the first provided path of the subscription is added
- each call to `SubscribePoll()` will return a subset of the matching paths
- once each path has been sent, no new updates are provided

I am testing on SR Linux.

**Comment by karimra** [comment]
>This is difficult to use tg.SubscribePoll() safely as we need to subscribe inside a go routine, then poll only when the goroutine has sufficiently moved forward to register the new subscription.

The client is supposed to wait for the first `sync_update: true`. That should indicate that the initial updates have been received.

> Also, I am unable to make it work at all:
> 
> * only the first provided path of the subscription is added
> * each call to `SubscribePoll()` will return a subset of the matching paths
> * once each path has been sent, no new updates are provided
> 
> I am testing on SR Linux.

I don't think SR Linux properly supports Poll subscription (or any other router AFIAK). If you want that kind of behavior, you will have better support using subscribe ONCE.
Or you can use gNMIc as a proxy.

**Comment by vincentbernat** [comment]
I don't receive the `sync_update` message, but you are right that the specification says it should happen. Let's close this issue then.
