### ISSUE TITLE
Possible to suppress empty messages?

### ISSUE THREAD

**Issue by bewing** [openconfig/gnmic#36]
I am dealing with a system that is mapping an internal database to arbitrary path elements in gNMI where keys are part of the elem path string, instead of actually being filterable keys.  As a result, I am doing a LOT of filtering on events, and in some cases, end up with messages (lists of Events) that are comprised of just empty events after using the `event-drop` filter to delete unwanted data.  The `file` output looks like this:

```
[
  {}
]
[
  {},
  {}
]
[
  {}
]
[
  {},
  {}
]
[
  {},
  {}
]
[
  {},
  {}
]
[
  {}
]
[
  {},
  {}
]
```

Is it possible to completely remove empty events from the message, and drop/suppress empty messages instead of writing them to outputs further downstream?

**Comment by karimra** [comment]
I think it should be doable to add a knob under the output, something like `ignore-empty: true`

**Comment by Sparc0** [comment]
would like this setting added also.

**Comment by karimra** [comment]
@bewing , @Sparc0  #61 makes the drop processor remove matching messages from the events list. The messages won't make it to the downstream outputs.
