### ISSUE TITLE
Query about gnmi proto version

### ISSUE THREAD

**Issue by ektanehwal** [openconfig/gnmic#369]
Which is the current gnmi proto version used in gnmic version : 0.34.3?
When are you planning to support gnmi.proto 0.10.0 ?
And how we can switch between different gnmi proto versions while using gnmic client?

**Comment by karimra** [comment]
v0.10.0, you can find it [here](https://github.com/openconfig/gnmic/blob/main/go.mod#L41)

**Comment by ektanehwal** [comment]
Thanks. Is there any way to use different proto version while using gnmic client ? Or gnmic which is compatible with any other proto version say 0.7.0 is present somewhere?

**Comment by karimra** [comment]
That would be a very old version... Do you see something break with your device when using the latest gNMIc version ? I think most of the proto updates were done in a backwards compatible way.

**Comment by ektanehwal** [comment]
No, nothing breaks. I was just curious to know this. 
Thanks for such quick response.
