### ISSUE TITLE
Golang 1.19 support

### ISSUE THREAD

**Issue by bewing** [openconfig/gnmic#37]
Attempting to use the API with Golang 1.19 results in another unsafe GC panic

```
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
        /home/bewing/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20211027215541-db492cf91b37/untested.go:25 +0x1f4
exit status 2
```

Based on the previous issue with 1.18, it again appears related to gomplate: https://github.com/hairyhenderson/gomplate/issues/1467

The upstream fix is first in 3.11.2:  https://github.com/hairyhenderson/gomplate/releases/tag/v3.11.2
3.11.0 has some deprecation notes that probably need to be checked:  https://github.com/hairyhenderson/gomplate/releases/tag/v3.11.0

**Comment by karimra** [comment]
This is in my todo list

**Comment by karimra** [comment]
Golang version bumped to 1.19.5 in gnmic v0.29.0, please give it a try
