### ISSUE TITLE
Limiting verbosity of loader results

### ISSUE THREAD

**Issue by jhujhiti** [openconfig/gnmic#38]
I'm using file-based discovery to load a growing number of subscription targets pulled from an inventory system. Each time the loader runs, it emits a log message like

```
2023/02/01 21:49:48.721392 [file_loader] result: map[targeta:{"name":"targeta","address":"192.0.2.1:1234","username":"gnmic","password":"****","timeout":2000000000,"skip-verify":true,"tags":[]} targetb:{"name":"targetb","address":"192.0.2.2:1234","username":"gnmic","password":"****","timeout":2000000000,"skip-verify":true,"tags":[]}]
```

With the full list of loaded targets every time the file is checked. This will grow to an unmanageable length pretty quickly. I'd like the ability to change the verbosity of these messages (maybe "loaded N targets") or turn them off entirely. Alternatively, logging only the targets that have changed would be nice.

**Comment by karimra** [comment]
Agree
