### ISSUE TITLE
My Prometheus is unable to scrape any telemetry data from gnmic for BGP operational state although gnmic is collecting data from the target and exposing it on port 9273.

### ISSUE THREAD

**Issue by arbabali999** [openconfig/gnmic#404]
PFB prometheus.yml and gnmic.yml. My Prometheus is unable to scrape any telemetry data from gnmic for BGP operational state although gnmic is collecting data from the target and exposing it on port 9273.

prometheus.yml:
------------------

scrape_configs:

job_name: "Prometheus"
static_configs:
targets: ["localhost:9090"]

job_name: "gnmic"
static_configs:
targets: ["localhost:9273"]

job_name: "Grafana"
static_configs:
targets: ["localhost:3000"]

gnmic.yml:
------------

port: 57400
timeout: 10s
insecure: true

targets:
192.168.69.38:
username: admin
password: admin123
subscriptions:
- sros_port_stats
- sros_ce_port_stats
- sros_cpu
- sros_memory_pool
- sros_anysec_stats
- sros_bgp_state

subscriptions:
sros_cpu:
paths:
- "/state/system/cpu[sample-period=60]/summary/usage"
mode: stream
stream-mode: sample
sample-interval: 5s

sros_memory_pool:
paths:
- "/state/system/memory-pools"
mode: stream
stream-mode: sample
sample-interval: 5s

sros_port_stats:
paths:
- "/state/port[port-id=1/1/c2/1]/statistics"
- "/state/port[port-id=1/1/c3/1]/statistics"
- "/state/port[port-id=1/1/c33/1]/statistics"
- "/state/port[port-id=esat-1/1/1]/statistics"
- "/state/port[port-id=esat-1/1/3]/statistics"
- "/state/port[port-id=esat-1/1/4]/statistics"
- "/state/port[port-id=esat-1/1/5]/statistics"
- "/state/port[port-id=esat-1/1/6]/statistics"
- "/state/port[port-id=esat-1/1/8]/statistics"
mode: stream
stream-mode: sample
sample-interval: 5s

sros_ce_port_stats:
paths:
- "/state/port[port-id=1/1/c27/1]/statistics"
- "/state/port[port-id=1/1/c28/1]/statistics"
- "/state/port[port-id=1/1/c29/1]/statistics"
mode: stream
stream-mode: sample
sample-interval: 5s

sros_bgp_state:
    paths:
      - "/state/router/bgp/neighbor/statistics/session-state"
    mode: stream
    stream-mode: sample
    sample-interval: 5s

outputs:
prom:
type: prometheus
listen: :9273
path: /metrics
metric-prefix: gnmic
append-subscription-name: true
export-timestamps: true
debug: false
event-processors:
- trim-prefixes
- esa-health

processors:
GNU nano 6.2
trim-prefixes:
event-strings:
value-names:
- ".*"
transforms:
- path-base:
apply-on: "name"

esa-health:
event-strings:
value-names:
- hardware-status
- power-supply-1-status
- power-supply-2-status
- fan-status
- temperature-status
transforms:
- replace:
apply-on: "value"
old: "ok"
new: "1"
- replace:
apply-on: "value"
old: "degraded"
new: "0"
- replace:
apply-on: "value"
old: "unknown"
new: "2"
- replace:
apply-on: "value"
old: "failed"
new: "3"

I have verified using below command (providing one as reference) about subscription path provided in gnmic.yml that subscriptions are correct.

[
  {
    "source": "192.168.69.38:57400",
    "timestamp": 1711626595652121572,
    "time": "2024-03-28T16:49:55.652121572+05:00",
    "updates": [
      {
        "Path": "state/router[router-name=Base]/bgp/neighbor[ip-address=192.168.100.1]/statistics/session-state",
        "values": {
          "state/router/bgp/neighbor/statistics/session-state": "Established"
        }
      }
    ]
  }
]

But http://localhost:9273/metrics doesn't show anything related to BGP operational state although other metrics are reflecting. 

Need assistance.

**Comment by karimra** [comment]
Prometheus accepts float values only, the BGP operational state is a string (`Established`). In order to show it in Prometheus you have to map it to a number (just like you did with the `esa-health` processor)

**Comment by arbabali999** [comment]
That worked. Thanks.
