### ISSUE TITLE
YANG model to Influx DB data type mappings

### ISSUE THREAD

**Issue by bradsowden** [openconfig/gnmic#42]
Hi,

I'm testing gNMI subscriptions to a Nokia SROS device in order to collect counter information and ultimately send this to Influx DB.

I've encounted a few issues with the gnmic Influx output data types and would be grateful for any feedback on the points below.

1) With gNMI JSON encoding, I observed 64-bit YANG numeric types are mapped to strings in the InfluxDB output. RFC7951 ("JSON Encoding of Data Modeled with YANG") states 64-bit numeric values should be represented as JSON strings and I assume this is why the corresponding InfluxDB output is also a string. I also assume there is nothing gnmic can do about this as it doesn't know the original YANG type and this is a limitation of JSON encoding.

2) With gNMI BYTES encoding, 64-bit YANG numeric values are mapped to numeric types in the Influx output as desired. However, I observed some errors in the gnmic Influx output logs and this appears to be due to the Nokia YANG model using "type union" for some counters. The Nokia documentation says the type sent for a particular counter depends on the value at that sample and in the example below you can see the "operational_pir" counter is first sent as an int64, which sets the data type for the counter on the Influx server, but the next sample is of type string and this results in an Influx error "field type conflict" because the data type has changed. Again, I assume there is nothing gnmic can do about this as it doesn't know the original YANG type is a union.

>_Example_
>
> gnmic Influx output for counter "operational_pir" (type int) - sample 1
> `> myport,path=/state/port/network/egress/queue/hardware-queue,port_id=1/x1/1/c18/1,queue_id=8,source=10.125.7.99 <more fields>,network/egress/queue/hardware_queue/operational_pir=1000000i,<more fields> 1676273979998510780`
> 
> gnmic Influx output -Influx output for counter "operational_pir" (type string) - sample 2 
> `myport,path=/state/port/network/egress/queue/hardware-queue,port_id=1/x1/1/c18/2,queue_id=1,source=10.125.7.99 <more fields>,network/egress/queue/hardware_queue/operational_pir="max",<more fields> 1676273980016682122`
> 
> gnmic Influx output log
> `2023-02-13T07:39:48Z E! [outputs.influxdb_v2] Failed to write metric to sros (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field `
>
> 
> Nokia YANG model type for the above counter
> ```
> 	typedef int-max {
> 		type union {
> 			type enumeration {
> 				enum "max"                          { value -1; }
> 			}
> 			type int64;
> 		}
> 		description "Maximum 64-bit value with max as -1";
> 	}
> ```

3) Lastly, I tried gNMI PROTO encoding and the Influx output appears to have all fields defined as strings. In theory, I assume gnmic has full access to YANG type information via the proto file but there is no existing gnmic functionality to set the Influx data types to anything other than string (or deal with the union type scenario described in item 2).

> gnmic Influx output log
> `default-1676519390,source=10.125.7.99:57400 //state/port.0/portId/value="B/1",//state/port.0/statistics/inBroadcastPackets/value="3968555",//state/port.0/statistics/inOctets/value="304900821",//state/port.0/statistics/inPackets/value="4003444",//state/port.0/statistics/inUnicastPackets/value="34889",//state/port.0/statistics/outBroadcastPackets/value="20",//state/port.0/statistics/outOctets/value="6473925",//state/port.0/statistics/outPackets/value="46584",//state/port.0/statistics/outUnicastPackets/value="46564" 1676519424779419247`

In an ideal world, I would like the YANG model and Influx data types to be aligned as much as possible and it seems BTYES encoding is the best way to achieve this at the moment. To workaround the union quirk, I'm also looking at the OpenConfig YANG models rather than Nokia models as on the surface it appears they make less use of the problematic union types.

Thanks for any feedback.

**Comment by hellt** [comment]
Hi @bradsowden 
yes, you are correct about 1); this is a limitation of JSON encoding. And yes, currently Bytes encoding seems to be a way to deal with int64 counters.

I am not an expert on SR OS gNMI implementation, but I suspect the reason you see both a counter and a string (`"max"`) for a PIR value is that the value first stays in the boundaries where it can be reported as int64, but then it crosses the maximum threshold at which it is reported back as `"max"`.

My suggestion is for you to have a look at [gnmic processors](https://gnmic.openconfig.net/user_guide/event_processors/intro/), where you can massage incoming data and, for example, convert `"max"` to `-1` (or max int64) to keep the integer type consistent.

You probably don't want to drop that counter entirely (it is possible with processors), since this might be a useful insight.

**Comment by bradsowden** [comment]
Thanks for the feedback. I hadn't yet explored the gnimc processors but they look quite powerful.

I'll also spend some time assessing how many, and what specific counters, we are interested in collecting to see how scalable it is to use processors for our use case.

Thanks
Brad
