### ISSUE TITLE
Getting error "String field 'gnmi.PathElem.key' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes."

### ISSUE THREAD

**Issue by kapilrastogi1231** [openconfig/gnmic#436]
While running get request getting below error with PROTO encoding:
"String field 'gnmi.PathElem.key' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes."
Can anyone please help to understand and resolve this issue? gRPC server is written in C++ and latest gRPC stack is in use (1.60.0).

**Comment by karimra** [comment]
Looks like an error coming from server side.
