### ISSUE TITLE
how to intall the  gnmic wihtout the sudo permissions 

### ISSUE THREAD

**Issue by tmaliped-1** [openconfig/gnmic#443]
how to intall the  gnmic wihtout the sudo permissions 

user tmaliped is not allowed to execute '/usr/bin/cp -f /tmp/tmp.SW2DdtCEH6/gnmic /nobackup/tmaliped/gnmic/gnmic' as root on sjc-ads-7136.

**Comment by karimra** [comment]
You can manually download the right binary/package from the release page: https://github.com/openconfig/gnmic/releases/tag/v0.37.0 and place it where it makes sense to you.
