### ISSUE TITLE
after copying the file  when installing it is asking for the root permissions . how do i bypass this

### ISSUE THREAD

**Issue by tmaliped-1** [openconfig/gnmic#445]
You can manually download the right binary/package from the release page: https://github.com/openconfig/gnmic/releases/tag/v0.37.0 and place it where it makes sense to you.

copied the file on linux , But when installing i saw this error 

<pre>ls
<font color="#00D700">gnmic</font>  <font color="#EF2929">gnmic_0.37.0_Linux_x86_64.tar.gz</font>  LICENSE  README.md
sjc-ads-7136:47&gt; cd gn
gnmic*                            gnmic_0.37.0_Linux_x86_64.tar.gz 
sjc-ads-7136:47&gt; cd gnmic
/ws/tmaliped-sjc/gnmic 
sjc-ads-7136:48&gt; ls
<font color="#0087FF">gnmic</font>
sjc-ads-7136:49&gt; cd gnmic/
sjc-ads-7136:50&gt; ls
<font color="#0087FF">cmd</font>          Dockerfile  goreleaser-alpine.dockerfile   LICENSE     README.md
config.json  <font color="#0087FF">docs</font>        goreleaser-scratch.dockerfile  main.go     <font color="#0087FF">tests</font>
config.toml  <font color="#0087FF">examples</font>    go.sum                         mkdocs.yml
config.yaml  go.mod      <font color="#00D700">install.sh</font>                     <font color="#0087FF">pkg</font>
sjc-ads-7136:51&gt; ls -al install.sh 
-rwxrwxrwx. 1 tmaliped eng 9764 May  6 14:31 <font color="#00D700">install.sh</font>
sjc-ads-7136:52&gt; ./install.sh 

Sorry, user tmaliped is not allowed to execute &apos;/usr/bin/cp -f /tmp/tmp.qaIhanFFmf/gnmic /usr/local/bin/gnmic&apos; as root on sjc-ads-7136.
Failed to install gnmic
	For support, go to https://github.com/openconfig/gnmic/issues
sjc-ads-7136:53&gt; 
</pre>

**Comment by hellt** [comment]
you need to untar the downloaded https://github.com/openconfig/gnmic/releases/download/v0.37.0/gnmic_0.37.0_Linux_x86_64.tar.gz file where you would find the `gnmic` binary

**Comment by tmaliped-1** [comment]
Yes i did it . There is no. need for running the install.sh file
