### ISSUE TITLE
Error : Maximum number of EOS subscribe requests reached

### ISSUE THREAD

**Issue by viinay** [openconfig/gnmic#460]
Hi,

I am getting this error for gnmic subscription. I have 13 subscription with 1 path in each subscription. I am using Juniper routers. 

**"target "ed5808e3-202f-4fe8-aa53-bc78aa2ad1a9": subscription system-facts rcv error: rpc error: code = OutOfRange desc = Maximum number of EOS subscribe requests reached"**

1. How to increase the subscription limit using gnmic ?
2. Are this subscription at the device level?

**Comment by LimeHat** [comment]
`code = OutOfRange desc = Maximum number of EOS subscribe requests reached`
is an error from the device, you should check with the device vendor

**Comment by XioNoX** [comment]
@LimeHat we started hitting that issue, as well, did you figure out how to solve it? Thanks
