### ISSUE TITLE
split-events: false not suppressing empty messages

### ISSUE THREAD

**Issue by zenodhaene** [openconfig/gnmic#472]
I'm experimenting with the "event-drop" filter, and I'm wondering whether the following is intended behavior:

When the event-drop filter rejects all events in a message, the content of the message is None.
- When `split-events: true` is set on the output, no messages are received
- When `split-events: false` is set on the output, a message is returned every 5 seconds (my sample interval), but with value "None"

My configuration:
```
...
targets:
  srl-1:57400:
    subscriptions:
      - srl_name

subscriptions:
  srl_name:
    paths:
      - /system/name/host-name
    mode: stream
    stream-mode: sample
    sample-interval: 5s

outputs:
  kafka-output:
    type: kafka
    address: <redacted>:9092
    topic: testtoppic
    max-retry: 2
    timeout: 5s
    recovery-wait-time: 10s
    format: event
    override-timestamps: false
    buffer-size: 0
    enable-metrics: true
    debug: true
    split-events: true
    event-processors:
      - drop-empty

processors:
  drop-empty:
    event-drop:
      tags:
      - ".*"
```

Example message when `split-events: false` is configured:
![image](https://github.com/openconfig/gnmic/assets/7818471/8577d2dc-8ab3-4ee8-b503-e13b72b12415)

Is there any way to achieve the same behavior when `split-events: false` is configured? I.e., no message is sent if all messages are filtered out?

**Comment by karimra** [comment]
There is no way to suppress the empty list of events using processors, I added that behavior in #473

**Comment by zenodhaene** [comment]
Thanks @karimra for the very speedy implementation! I tested it, and it works as expected.

When can we expect this feature to be released in the official image?

**Comment by karimra** [comment]
Hey Zeno, v0.38.0 should have the fix. Thanks for reporting this!
