### ISSUE TITLE
Installation script fails with ubuntu 24.04

### ISSUE THREAD

**Issue by pklepikov** [openconfig/gnmic#488]
Installation script doesn't work anymore. Tried 2 options and both fail

###Direct install 

`
bash -c "$(curl -sL https://get-gnmic.openconfig.net)"
Downloading https://github.com/openconfig/gnmic/releases/download/null/gnmic_ull_linux_x86_64.tar.gz
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to install gnmic
        For support, go to https://github.com/openconfig/gnmic/issues
`
###Install using pkg option:

`
bash -c "$(curl -sL https://get-gnmic.openconfig.net)" -- --use-pkg
Downloading https://github.com/openconfig/gnmic/releases/download/null/gnmic_ull_linux_x86_64.deb
Preparing to install gnmic ull from package
dpkg-deb: error: unexpected end of file in archive magic version number in /tmp/tmp.zWqBKlXYsp/gnmic_ull_linux_x86_64.deb
dpkg: error processing archive /tmp/tmp.zWqBKlXYsp/gnmic_ull_linux_x86_64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/tmp.zWqBKlXYsp/gnmic_ull_linux_x86_64.deb
`

**Comment by hellt** [comment]
this is likely a gh rate limiting in action
you can invole curl separately and see the contents of the downloaded file
