### ISSUE TITLE
Unable to install gnmic on ads

### ISSUE THREAD

**Issue by vennvenk** [openconfig/gnmic#533]
I'm trying to install gnmic  on my workspace but facing the below error

[bgl-ads-5489:gnmi]#bash -c "$(curl -sL https://get-gnmic.openconfig.net)"
Downloading https://github.com/openconfig/gnmic/releases/download/v0.38.2/gnmic_0.38.2_linux_x86_64.tar.gz
Preparing to install gnmic 0.38.2 into /usr/local/bin

              .:|:.:|:.
                CISCO

[ This device requires Duo authentication   ]
[ For assistance: http://unixauth.cisco.com ]

Duo two-factor login for vennvenk

Enter a passcode or select one of the following options:

 1. Duo Push to +XX XXXXX X5132

Passcode or option (1-1): 

Pushed login request 53V5 to your device...
Success. Logging you in...
Sorry, user vennvenk is not allowed to execute '/bin/cp -f /tmp/tmp.86uc8RZJFl/gnmic /usr/local/bin/gnmic' as root on bgl-ads-5489.
Failed to install gnmic
	For support, go to https://github.com/openconfig/gnmic/issues
[bgl-ads-5489:gnmi]#

Could you please resolve the above issue.
<img width="433" alt="gnmi" src="https://github.com/user-attachments/assets/4f190d5e-bb52-4def-b63a-559ce045d771">

**Comment by hellt** [comment]
you can directly download the binary for your target architecture from the [releases](https://github.com/openconfig/gnmic/releases)
