### ISSUE TITLE
Prometheus output metrics type

### ISSUE THREAD

**Issue by sk4mi** [openconfig/gnmic#534]
Hello,

I've configured a gnmic to subscribe to interfaces counters, it works well and can be outputed as prometheus metrics.

```
# HELP nxos_openconfig_interfaces_interface_state_counters_in_discards gNMIc generated metric
# TYPE nxos_openconfig_interfaces_interface_state_counters_in_discards untyped
nxos_openconfig_interfaces_interface_state_counters_in_discards{interface_name="eth1/1",source="nexus-test",subscription_name="oc-interface",target="nexus-test"} 0
```

For example it expose this metric, but the type is `UNTYPED`. 
And when i'm trying to rate it with promql it do not works. I've this error message: `ranges only allowed for vector selectors`

How do you play with your prometheus metrics when they are untyped ? 

And can we change type for a given metric ?

**Comment by karimra** [comment]
The rate function works fine with untyped metrics. Can you share the promql expression that got you that error?
It's not possible to change the type of a metric.

**Comment by sk4mi** [comment]
I tested this expression first: 
`rate(nxos_openconfig_interfaces_interface_state_counters_in_discards{})[1m]` which returned `Error executing query: invalid parameter "query": 1:72: parse error: ranges only allowed for vector selectors`

I manage to rate it with this one:
`rate({__name__=~"nxos_openconfig_interfaces_interface_state_counters_in_discards"}[1m])`

Is this the good way to do it ?

**Comment by sacckth** [comment]
yeah, the rate interval goes inside the brackets: https://prometheus.io/docs/prometheus/latest/querying/functions/#rate

**Comment by sk4mi** [comment]
Oh sh*** 😮‍💨 

Sorry for noise and this dumb mistake ^^

Thanks guys
