### ISSUE TITLE
Removing the full path from the field in InfluxDB output

### ISSUE THREAD

**Issue by gavmckee80** [openconfig/gnmic#66]
How do I remove the full path from the field name in the influxdb output ?  I just want the name e.g. `in-broadcast-pkts` not the entire `/interfaces/interface/state/counters/in-broadcast-pkts` is this possible ?

```
from(bucket: "network-counters")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "interface_counters")
  |> filter(fn: (r) => r["source"] == "10.127.5.11")
  |> filter(fn: (r) => r["_field"] == "/interfaces/interface/state/counters/in-broadcast-pkts")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

**Comment by karimra** [comment]
yes there is a processor just for that, check this example: https://gnmic.openconfig.net/user_guide/event_processors/event_strings/#path-base

and here on how to apply processors on outputs: https://gnmic.openconfig.net/user_guide/event_processors/intro/#linking-an-event-processor-to-an-output
