### ISSUE TITLE
Listen mode: source/hostname

### ISSUE THREAD

**Issue by lemontree61089** [openconfig/gnmic#8]
Hello,

I am using gnmic in listen mode for dial-out telemetry with Nokia SROS routers. I noticed that the node hostname is not streamed with data. I get instead the source with the format _ip_address:port_
Is there a way to associate the hostname of the node instead of the ip_address? I am aware it is possible to stream the hostname, but what I would like to do is to have the hostname directly associated with the data

**Comment by karimra** [comment]
Hi, do you want to associate the hostname configured on the node?
Let check if that hostname is sent in the http headers.

Meanwhile, what you could do is configure the router hostname in your gnmic file and populate /etc/hosts with the corresponding IP addresses.

**Comment by lemontree61089** [comment]
Yes I would like to associate the node hostname.

So far, I am streaming the node hostname on a dedicated measurement (I'm using influxdb). And then use the IP address node to link to other measurement.
For a human, it is obviously easier to select based on a hostname instead of an IP address.

**Comment by karimra** [comment]
It looks like SROS sends both the system-name and the subscription-name as http2_headers, I will add those two as labels.
