### ISSUE TITLE
`gnmic diff` for comparing SetRequests, SetRequest & Notifications

### ISSUE THREAD

**Issue by wenovus** [openconfig/gnmic#80]
I'm wondering if gnmic would be open to incorporating this functionality that's currently implemented in ygot here (README has examples): https://github.com/openconfig/ygot/tree/master/gnmidiff

Proposed commands (open to changing command names):

### Compares intent between two SetRequests
`gnmic diff setrequest cmd/demo/setrequest2.textproto cmd/demo/setrequest.textproto`

### Compares whether after a SetRequest has been applied, the notifications that you get back from the device are consistent with the input SetRequest
`gnmic diff setrequest-to-notifs cmd/demo/setrequest.textproto cmd/demo/notifs.textproto`

Any suggestions on how to improve usability are appreciated. I think the meaning of these commands might be fuzzy at first, especially the last one. I'm thinking of just making it clear in the command description.

**Comment by karimra** [comment]
I think this will be a great addition. 

gnmic already has a diff command (https://gnmic.openconfig.net/cmd/diff/), it compares a set of values between a reference target and a list of N other targets. It does that by retrieving the values from all the targets using `Get` or `Subscribe` ONCE.  So it's essentially comparing Notifications.

I believe it's ok to implement the above commands as subcommands of the existing `diff` if you don't mind.
This is a personal preference but I'm not a big fan of positional arguments, I prefer flags. Flags make the command more readable and extensible.
Positional arguments are ok if it's a single arg or a set of args of the same type.

This functionality will be a good starting base for implementing a `Set` and `Verify` command.
