### ISSUE TITLE
Troubleshooting RAM Usage

### ISSUE THREAD

**Issue by ebinachan** [openconfig/gnmic#81]
Hi,

Great work on gNMIc, we've been using it in dial-out mode with processors for almost a year now!
Recently, we noticed an issue where the gnmic process grabs a lot of RAM and eventually fills up the VM (in 15-20minutes).
I think it started once we deployed more than 230 7250 IXR-e nodes. The forecast for this year is to double this amount.
This is the currently used node template: https://github.com/ebinachan/telemetry/blob/master/sros/ixr_dialout_telemetry_template.txt

What would be the best way to troubleshoot this?

Many thanks,
EC
![20230326_gnmic_RAM_tshoot_32gb](https://user-images.githubusercontent.com/52893423/227901795-47f22ab2-ec04-4c62-b61d-f9d199a1deca.jpg)

**Comment by karimra** [comment]
The bottleneck could be on the output side.

Do you see all the metrics being written to influxDB? 
You can tweak `batch-size: 1000` (set to a lower value) and `flush-timer: 10s` (set to lower value) to speed up the flushing of metrics to the DB and avoid storing them in memory.

**Comment by ebinachan** [comment]
Yes! I've disabled the event-processors for the influxdb output and RAM usage stays low.
This is the template I've been using, output1 was already disabled:
https://github.com/ebinachan/telemetry/blob/master/sros/gnmic.yaml

I'll try to rewrite the processors regexes, to match on exact field value names, instead of ".*something$", see if this changes things.

EC

**Comment by karimra** [comment]
Thanks for the update! Glad the ram issues are gone.
