### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by richardeaxon** [openconfig/gnmic#83]
This page in the docs has a link to Github discussions which does not work.

https://gnmic.openconfig.net/deployments/deployments_intro/

On the old archived repo discussions were enabled. 

Also, how do we ask for help with gnmic if discussions is no longer an option.

Thanks.

**Comment by karimra** [comment]
Thanks, will update it.
I think issues are fine to ask for help, just like before discussions were introduced.
